name: Feature Request
description: Suggest a new feature for ResearchBridge
labels: ["enhancement"]
body:
  - type: textarea
    attributes:
      label: Feature Description
      description: What problem does this solve?