name: Build and deploy Node.js app to Azure Web App - researchbridge

on:
  push:
    branches:
      - feature/Gabriel
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install Dependencies
        run: |
          if [ -f package-lock.json ]; then
            npm ci --ignore-scripts
          else
            echo "No lock file found, skipping npm ci"
          fi
        shell: bash

      - name: Run Build Script
        run: npm run build

      - name: Run Tests
        run: npm test

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_48E69B7DC7D14F84ABE581FDDCD25AF8 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_936F564B510D4B4DBF9C1B3BC5FD7776 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_3D3AAD5C41E541F8B3847CB3C99520B0 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'researchbridge'
          package: .
