name: ResearchBridge CI/CD

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths-ignore: ['docs/**', 'README.md']
  pull_request:
    branches: [main]

jobs:
  validate:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    permissions:
      contents: write
      checks: write

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        cache: 'npm'

    - name: Generate Lock File
      run: |
        if [ ! -f package-lock.json ]; then
          echo "🔧 package-lock.json not found. Attempting to generate..."
          npm install --package-lock-only || { echo "❌ Failed to generate lock file"; exit 1; }
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add package-lock.json
          git commit -m "Generate package-lock.json" || echo "⚠️ No changes to commit"
        else
          echo "✅ package-lock.json already exists"
        fi
      shell: bash

    - name: Install Dependencies
      run: |
        if [ -f package-lock.json ]; then
          npm ci --ignore-scripts
        else
          echo "No lock file found, skipping npm ci"
        fi
      shell: bash
    
    - name: Lint Code
      run: npx eslint . --ext .js,.jsx,.ts,.tsx
     

    - name: Security Audit
      run: npm audit --audit-level=moderate

    - name: Run Tests with Coverage
      run: npm run test:coverage

    - name: Upload Coverage Report
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report-${{ matrix.os }}
        path: coverage

    - name: Debug Info
      run: |
        echo "Git status:"
        git status
        echo "List of files:"
        ls -la
      shell: bash
